// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrwviYOHCQxVOjASiiP92Zh7ggcj1OfU',
    appId: '1:921959811180:android:3c77d4e99b9bc9dc0b7049',
    messagingSenderId: '921959811180',
    projectId: 'snacks-app-23',
    storageBucket: 'snacks-app-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASFWVk0xdpJQZ0-IX2F9PQO6K6OQneXQE',
    appId: '1:921959811180:ios:b31db5b731bfb5f60b7049',
    messagingSenderId: '921959811180',
    projectId: 'snacks-app-23',
    storageBucket: 'snacks-app-23.appspot.com',
    androidClientId: '921959811180-3jtbcsg6t35uib5p1bt0qhctfnef8g14.apps.googleusercontent.com',
    iosClientId: '921959811180-nmkjt6glr13aq216j5g95kms6lc0ivov.apps.googleusercontent.com',
    iosBundleId: 'com.snacks.snacksProApp',
  );
}
