class AppRoutes {
  static String get home => '/home';
  static String get stock => '/stock';
  // static String get start => '/start';
  static String get phoneAuth => '/phone-auth';
  static String get otp => '/otp';
  // static String get address => '/address';
  static String get success => '/success';
  static String get scanQrCode => '/scan-qr';
  static String get rechargeCard => '/recharge-card';
  static String get cart => '/cart';
  // static String get item => '/item';
  // static String get payment => '/payment';
  static String get newItem => '/new-item';
  static String get updateImage => '/update-image';
  static String get orders => '/orders';
  static String get restaurantAuth => '/restaurant-auth';
  // static String get selectRestaurant => '/select-restaurant';
  static String get scanCard => '/scan-card';
  static String get passwordScreen => '/pass';
  static String get finance => '/finance';
  static String get newEmployee => '/new-employee';
  static String get newRestaurant => '/new-restaurant';
  static String get addBankAccount => '/add-bank-account';
  static String get unathorizedAuth => '/unathorized-auth';

  // '/': (context) => const StartScreen(),
  // '/': (context) => const SelectRestaurantScreen(),
  // '/': (context) => const PhoneAuthenticationScreen(),
  // '/': (context) => AddAddressScreen(),
  // '/': (context) => const PhoneNumberScreen(),
  // '/': (context) => const SuccessScreen(),
  // '/': (context) => const ScanCardScreen(),
  // '/': (context) => const RechargeCardScreen(),
  // '/': (context) => const HomeScreen(),
  // '/': (context) => const ItemScreen(),
  // '/': (context) => const MyCartScreen(),
  // '/': (context) => const PaymentScreen(),
  // '/': (context) => const NewItemScreen(),
  // '/': (context) => const OrdersScreen(),
  // '/': (context) => const HomeScreen(),
  // '/': (context) => const HomeScreen(),
  // '/': (context) => const RestaurantAuthenticationScreen(),
}
